version: '2'

volumes:
  webroot:
    driver: local

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    links:
      - db
    volumes:
      - webroot:/var/www/todobackend
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.release
      MYSQL_HOST: db
      MYSQL_USER: raj
      MYSQL_PASSWORD: password
    command:
      - uwsgi
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--master"
      - "--die-on-term"

  test:
    image: phullr2/todobackend-specs:latest 
    links: 
      - nginx
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /reports/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: --reporter mocha-jenkins-reporter

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    links:
      - app  
    ports:
      - "8000:8000"     
    volumes:
      - webroot:/var/www/todobackend

  db:
    image: mysql:5.6
    expose: 
      - "3306"
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: raj
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  agent:
    image: phullr2/todobackend-ansible:latest
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: 3306
    command: ["probe.yml"]
  
